name: Server

on:
  push:
    branches:
      - server

jobs:
  build:
    name: Build server
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 22

      - name: install npm
        run: npm i -g npm@latest

      - name: install dependencies
        run: npm i

      - name: start server
        run: node app.js

      
